### ISSUE TITLE
Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [bevacqua/hget#4]
Dear Nicolás,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by bevacqua** [comment]
Sorry, no. Feel free to clone and do that yourself.
