### ISSUE TITLE
Advice: Output to .txt file?

### ISSUE THREAD

**Issue by mitchellknight** [bevacqua/hget#5]
`hget` is would be a great tool for grabbing text content from websites for editing. The only issue I'm having is how to get the output in to a _.txt_ file without paragraphs having a bunch of line breaks.

```command
hget example.com > test.txt
```

This creates a bunch of lines breaks in paragraphs that aren't in the HTML.

```command
output=$(hget example.com)
echo -n $output > test.txt
```

This removes all line breaks including the ones I want (between paragraphs).

Any advice? It's probably obvious but I'm out of ideas.

**Comment by bevacqua** [comment]
Not sure what you mean. Can you provide an actual example that can be reproduced?
